apiVersion : apps/v1
kind: Deployment
metadata:
  name: venkateshypipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: venkateshypipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: venkateshypipelinesjavascriptdocker 
    spec:
      containers:
        - name: venkateshypipelinesjavascriptdocker 
          image: myacrrepo9543.azurecr.io/venkateshypipelinesjavascriptdocker
          ports:
          - containerPort: 9090