apiVersion: v1
kind: Service
metadata:
    name: venkateshypipelinesjavascriptdocker
spec:
    type: LoadBalancer
    ports:
    - port: 9090 
    selector:
        app: venkateshypipelinesjavascriptdocker